# https://lychee.cli.rs/#/usage/config

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs
cache = true

# Discard all cached requests older than this duration
max_cache_age = "1d"

#############################  Exclusions  ##########################

exclude = [
  # Ignore all URLS with "$" - BASH variable in URL
  '.*\$.*',
]
