FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:1-51

USER root

# Create and change to the app directory
WORKDIR /opt/app-root

# Copy application dependency manifests to the container image
COPY package.json ./

# Install dependencies
RUN npm install

# Copy local code to the container image
COPY . ./

HEALTHCHECK --interval=4s --timeout=3s --retries=5 \
  CMD curl -f http://localhost:${PORT} || exit 1

USER 1001

# Run the web service on container startup
CMD [ "npm", "start" ]
