FROM registry.access.redhat.com/ubi9/nodejs-16-minimal@sha256:2821786eecb235a2cd6124078d2ce8d8fbe25ba3a57695fc13ef1c5491a9becc

USER root

# Create and change to the app directory
WORKDIR /opt/app-root

# Copy application dependency manifests to the container image
COPY package.json ./

# Install dependencies
RUN npm install

# Copy local code to the container image
COPY . ./

USER 1001

# Run the web service on container startup
CMD [ "npm", "start" ]
