FROM registry.access.redhat.com/ubi9/nodejs-18-minimal@sha256:2b5b63f9df40ea9c90f54747e71efbd48b75f7d1a637dad3a5cce20884f87dbf

USER root

# Create and change to the app directory
WORKDIR /opt/app-root

# Copy application dependency manifests to the container image
COPY package.json ./

# Install dependencies
RUN npm install

# Copy local code to the container image
COPY . ./

USER 1001

# Run the web service on container startup
CMD [ "npm", "start" ]
