FROM registry.access.redhat.com/ubi9/nodejs-16-minimal@sha256:4499fa7b497f7abc2fb8a2e1dacc46f3ea2f8217c3861764bc23ed000cde0539

USER root

# Create and change to the app directory
WORKDIR /opt/app-root

# Copy application dependency manifests to the container image
COPY package.json ./

# Install dependencies
RUN npm install

# Copy local code to the container image
COPY . ./

USER 1001

# Run the web service on container startup
CMD [ "npm", "start" ]
