FROM registry.access.redhat.com/ubi9/nodejs-16-minimal:1-116

ENV PORT 8080

USER root

# Create and change to the app directory
WORKDIR /opt/app-root

# Copy application dependency manifests to the container image
COPY package.json ./

# Install dependencies
RUN npm install --cache /tmp/.npm && rm -rf /tmp/.npm

# Copy local code to the container image
COPY . ./

EXPOSE ${PORT}

HEALTHCHECK --interval=4s --timeout=3s --retries=5 \
  CMD curl -f http://localhost:${PORT} || exit 1

USER 1001

# Run the web service on container startup
CMD [ "npm", "start" ]
