name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: MegaLinter
        uses: megalinter/megalinter@v6.17.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          CSS_STYLELINT_FILTER_REGEX_EXCLUDE: src/app/static/css/main.css
          DISABLE_LINTERS: REPOSITORY_DEVSKIM
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: src/app/server.js
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (.github/|src/app/|.checkov.yml)
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
